Shop.WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using Shop.Domain.Entities;
using Shop.Domain.Abstract;
using Shop.WebUI.Models;
using System;

namespace GameStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IWareRepository repos;
        private IOrderProcessor orderProcessor;
        private IUserRepository userrepos;
        private IOrderRepository orderrepos;
        private IOrderWaresRepository orwarrepos;
        public CartController(IWareRepository repos, IOrderProcessor orderProcessor, IUserRepository userrepos, IOrderRepository orderrepos, IOrderWaresRepository orwarrepos)
        {
            this.repos = repos;
            this.orderProcessor = orderProcessor;
            this.userrepos = userrepos;
            this.orderrepos = orderrepos;
            this.orwarrepos = orwarrepos;
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }      

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            string userLogin = User.Identity.Name;
            User user = userrepos.Users.FirstOrDefault(u => u.Login == userLogin);
            
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                if (user != null)
                {
                    DateTime dt = DateTime.Now;
                    Order order = new Order
                    {
                        Date = dt,
                        User1 = user.Login,
                        Sum = cart.ComputeTotalValue()
                    };
                    orderrepos.SaveOrder(order);

                    OrderWare ow;

                    foreach (var item in cart.Lines)
                    {
                        ow = new OrderWare();
                        ow.OrderId = order.Id;
                        ow.UserId = user.ID;
                        ow.WareId = item.Ware.ID;
                        orwarrepos.SaveOrderWare(ow, cart);
                    }
                }
                //foreach (var item in cart.Lines)
                //{
                //    dbEntry.OrderId = orderware.OrderId;
                //    dbEntry.UserId = orderware.UserId;
                //    dbEntry.WareId = item.Ware.ID;
                //    context.SaveChanges();
                //}

                
                //orwarrepos.SaveOrderWare(ow, cart);

                orderProcessor.ProcessOrder(cart, shippingDetails);
                
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int Id, string returnUrl)
        {
            Ware ware = repos.Wares
                .FirstOrDefault(g => g.ID == Id);

            if (ware != null)
            {
                cart.AddItem(ware, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int Id, string returnUrl)
        {
            Ware ware = repos.Wares
                .FirstOrDefault(g => g.ID == Id);

            if (ware != null)
            {
                cart.RemoveLine(ware);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }       
    }
}

Shop.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.Domain.Abstract;

namespace Shop.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IWareRepository repos;

        public NavController(IWareRepository repos)
        {
            this.repos = repos;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repos.Wares
                .Select(ware => ware.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

Shop.WebUI/Controllers/WareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.Domain.Abstract;
using Shop.Domain.Entities;
using Shop.WebUI.Models;

namespace Shop.WebUI.Controllers
{
    public class WareController : Controller
    {
        private IWareRepository repos;
        public int pageSize = 6;
        public WareController(IWareRepository repos)
        {
            this.repos = repos;
        }

        public ActionResult List(string category, int page = 1)
        {
            WaresListViewModel model = new WaresListViewModel
            {
                Wares = repos.Wares
            .Where(p => category == null || p.Category == category)
            .OrderBy(game => game.ID)
            .Skip((page - 1) * pageSize)
            .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
        repos.Wares.Count() :
        repos.Wares.Where(game => game.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public ActionResult GetCurentWare(int Id)
        {
            Ware ware = repos.Wares.FirstOrDefault(w => w.ID == Id);

            return View(ware); 
        }
        public FileContentResult GetImage(int Id)
        {
            Ware ware = repos.Wares
                .FirstOrDefault(g => g.ID == Id);

            if (ware != null)
            {
                return File(ware.ImageData, ware.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

Shop.WebUI/Views/Shared/WareSummary.cshtml
@model Shop.Domain.Entities.Ware

@*<div class="well">
        <h3>
            <strong>@Model.Name</strong>
            <span class="pull-right label label-primary">@Model.Price.ToString("# грн")</span>
        </h3>
        <span class="lead">@Model.Description</span>
    </div>*@

<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-grid.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
</head>
<div class="well">
    @if (Model.ImageData != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" 
                 src="@Url.Action("GetImage", "Ware",
        new { Model.ID })" />
        </div>
    }
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# грн")</span>
    </h3>


    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-primary" value="Додати в кошик" />
        </div>
    }
    <span class="lead">@Model.Description</span>
</div>

Shop.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-grid.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        <div class="container">
            <div class="top-nav">
                <div class="row justify-content-between align-items-center">
                    <div class="col-md-auto">
                        <img class="logo-image" width="70px" src="~/Content/Images/Logo.png" />
                    </div>
                    <div class="col-md-auto">
                        <ul class="top-nav_menu">
                            <li>@Html.ActionLink("Головна", "List", "Ware", new { area = "" }, new { @class = "" })</li>
                            <li>@Html.ActionLink("Про компанію", "About", "Home", new { area = "" }, new { @class = "" })</a></li>
                            <li>@Html.ActionLink("Контакти", "Contacts", "Home", new { area = "" }, new { @class = "" })</li>
                            <li>@Html.ActionLink("Admin", "Index", "Admin", new { area = "" }, new { @class = "" })</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
}
        @RenderBody()
    </div>
</body>
</html>

Shop.WebUI/Views/Shared/_Layout.cshtml
@*<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("72rubla", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Link", "List", "Ware",new { area =""}, new { @class="navbar-brand"})
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-grid.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />

    <title>72 rubla</title>


    <style>
    </style>
</head>
<body>
    <div class="container">
        <div class="top-nav">
            <div class="row justify-content-between align-items-center">
                <div class="col-md-auto">
                <img class="logo-image" width="70px" src="~/Content/Images/Logo.png" />
                </div>
                <div class="col-md-auto">
                    <ul class="top-nav_menu">
                        <li>@Html.ActionLink("Головна", "List", "Ware", new { area = "" }, new { @class = "" })</li>
                        <li>@Html.ActionLink("Про компанію", "About", "Home", new { area = "" }, new { @class = "" })</a></li>
                        <li>@Html.ActionLink("Контакти", "Contacts", "Home", new { area = "" }, new { @class = "" })</li>
                        <li>@Html.ActionLink("Admin", "Index", "Admin", new { area = "" }, new { @class = "" })</li>
                        <li>@Html.ActionLink("Register", "Register", "Account", new { area = "" }, new { @class = "" })</li>
                        <li>|</li>
                        <li>@Html.ActionLink("Login", "Login", "Account", new { area = "" }, new { @class = "" })</li>
                    </ul>
                </div>
                <div class="col-md-auto">@Html.Action("Summary", "Cart")</div>
            </div>
        </div>        
    </div>

    <div class="container">
        <div class="row justify-content-between">
            <div class="col-md-3">
                <div class="left-sidebar">
                    <div id="categories" class="">
                        @Html.Action("Menu", "Nav")
                    </div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="content">
                    
                        @RenderBody()
                    
                </div>
            </div>
        </div>
    </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bondar</p>
        </footer>
</body>
</html>